// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacePark2;

namespace SpacePark2.Migrations
{
    [DbContext(typeof(SpaceParkContext))]
    partial class SpaceParkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpacePark2.Models.Parking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParkingHouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpaceTravellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StarShipId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParkingHouseId");

                    b.HasIndex("SpaceTravellerId");

                    b.HasIndex("StarShipId");

                    b.ToTable("Parking");
                });

            modelBuilder.Entity("SpacePark2.Models.ParkingHouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParkingHouse");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c07e5ed-a15a-46f5-a06e-2164ef7cceb0"),
                            Capacity = 4000.0,
                            Name = "Naboo Parking Complex"
                        },
                        new
                        {
                            Id = new Guid("6301dd96-c3f6-43dc-9047-563c8859d1c9"),
                            Capacity = 6000.0,
                            Name = "Hoth SpacePort"
                        });
                });

            modelBuilder.Entity("SpacePark2.Models.SpaceTraveller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpaceTraveller");
                });

            modelBuilder.Entity("SpacePark2.Models.StarShip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ShipLength")
                        .HasColumnType("float");

                    b.Property<string>("StarShipModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StarShip");
                });

            modelBuilder.Entity("SpacePark2.Models.Parking", b =>
                {
                    b.HasOne("SpacePark2.Models.ParkingHouse", "ParkingHouse")
                        .WithMany()
                        .HasForeignKey("ParkingHouseId");

                    b.HasOne("SpacePark2.Models.SpaceTraveller", "SpaceTraveller")
                        .WithMany()
                        .HasForeignKey("SpaceTravellerId");

                    b.HasOne("SpacePark2.Models.StarShip", "StarShip")
                        .WithMany()
                        .HasForeignKey("StarShipId");

                    b.Navigation("ParkingHouse");

                    b.Navigation("SpaceTraveller");

                    b.Navigation("StarShip");
                });
#pragma warning restore 612, 618
        }
    }
}
